Repository Dont12/KDT_Y_FE_Mini-Project, pull requests merged in 2023-11, with the labels that each got.

#14 Conf: set initial development environment
  public/fonts/inter-var-latin.woff2
  src/app/layout.tsx
  src/styles/global.css
  tailwind.config.ts
  vercel.json
Labels: Configure

#16 Feat : add static layout
  next.config.js
  package-lock.json
  public/images/cart.svg
  src/app/detail/page.tsx
  src/app/layout.tsx
  src/styles/global.css
Labels: enhancement, Configure

#18 Feat: add Header components with navigation links and logo
  package-lock.json
  package.json
  public/svg/Logo.svg
  public/svg/cartIcon.svg
  public/svg/homeIcon.svg
  public/svg/logo.svg
  public/svg/myPageIcon.svg
  src/app/cart/page.tsx
  src/app/detail/page.tsx
  src/app/mypage/page.tsx
  src/app/user/page.tsx
  src/components/Common/Header.tsx
  src/components/Common/HeaderNav.tsx
  src/components/common/tmp.tsx
  src/styles/global.css
Labels: enhancement

#19 Feature/header
  src/app/cart/page.tsx
  src/app/mypage/page.tsx
  src/components/common/Header.tsx
  src/components/common/HeaderNav.tsx
Labels: duplicate, design

#21 Set absolute path & Add signin, signup page
  .eslintrc.js
  src/app/auth/layout.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/signin/page.tsx
  src/app/signup/signup.tsx
  src/components/auth/ErrorMsg.tsx
  src/components/auth/SubmitButton.tsx
  src/components/auth/ValidationIcon.tsx
  src/components/auth/index.tsx
  src/components/auth/input/InputContact.tsx
  src/components/auth/input/InputEmail.tsx
  src/components/auth/input/InputName.tsx
  src/components/auth/input/InputPassword.tsx
  src/components/auth/input/InputPasswordConfirm.tsx
  src/hooks/auth/index.ts
  src/hooks/auth/useAuthInput.ts
  src/hooks/auth/useButtonActivate.ts
  tsconfig.json
Labels: enhancement

#32 Refactor: add component return type
  src/components/common/Header.tsx
  src/components/common/HeaderNav.tsx
Labels: refactor

#23 Feat: add Header Detail page
  package-lock.json
  package.json
  src/app/detail/[slug]/page.tsx
  src/app/detail/page.tsx
  src/app/layout.tsx
  src/components/common/Carousel.tsx
  src/components/common/DateRagePicker.tsx
  src/components/common/Toast.tsx
  src/components/detail/Detail.tsx
  src/components/detail/PersonInput.tsx
Labels: enhancement

#25 Feat: add Main, Category page
  package-lock.json
  package.json
  public/images/carousel01.jpg
  public/svg/mainIcon/condo.svg
  public/svg/mainIcon/guestHouse.svg
  public/svg/mainIcon/hanok.svg
  public/svg/mainIcon/homestay.svg
  public/svg/mainIcon/hotel.svg
  public/svg/mainIcon/minbak.svg
  public/svg/mainIcon/motel.svg
  public/svg/mainIcon/pension.svg
  public/svg/mainIcon/servicedResidences.svg
  public/svg/mainIcon/youthHostel.svg
  src/app/category/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/category/AccommodationCard.tsx
  src/components/category/Dropdown.tsx
  src/components/category/InfiniteScrollContainer.tsx
  src/components/category/YourItemComponent.tsx
  src/components/main/Carousel.tsx
  src/components/main/IconList.tsx
  src/components/main/IconWithLabel.tsx
  src/components/main/Navigation.tsx
  src/components/main/PensionCard.tsx
  tsconfig.json
Labels: enhancement, design

#29 Feat: add cart page layout & add date format function & remove global font class
  src/@types/cart.types.ts
  src/app/cart/page.tsx
  src/components/cart/CartFooter.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartNotice.tsx
  src/components/cart/cartItem/CartItem.tsx
  src/components/cart/cartItem/CartItemHeader.tsx
  src/components/cart/cartItem/CartItemRoomInfo.tsx
  src/components/cart/cartItem/EmptyCartItem.tsx
  src/components/cart/index.ts
  src/components/common/HeaderNav.tsx
  src/styles/global.css
  src/utils/dateFormat.ts
  tailwind.config.ts
Labels: enhancement, design

#35 Design: add footer
  public/svg/footerLogo.svg
  src/app/layout.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/footer/FooterButton.tsx
  src/components/common/footer/FooterGithub.tsx
  src/styles/global.css
  tailwind.config.ts
Labels: enhancement, design

#36 Design: update for SubmitButton component
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/components/common/SubmitButton.tsx
Labels: design

#40 Design: add className SubmitButton component
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/components/common/SubmitButton.tsx
Labels: design

#42 Refactor: modify SubmitButton component
  src/components/cart/CartFooter.tsx
Labels: refactor

#44 Feat: add functionality to group the same product in cart
  src/@types/cart.types.ts
  src/app/cart/page.tsx
  src/components/cart/cartItem/CartItem.tsx
  src/components/cart/cartItem/CartProductInfo.tsx
  src/components/cart/cartItem/CartRoomInfo.tsx
Labels: enhancement

#59 Feat: add Added mock API connection
  next.config.js
  package-lock.json
  src/@types/cart.types.ts
  src/api/cartRequest.ts
  src/app/cart/page.tsx
Labels: enhancement

#72 Feat: check guestCount valid with activating button
  package-lock.json
  src/@types/cart.types.ts
  src/@types/detail.types.ts
  src/@types/order.types.ts
  src/api/cartRequest.ts
  src/api/detailInfoRequest.ts
  src/app/api/orderRequest.ts
  src/app/detail/[id]/page.tsx
  src/components/detail/CartButton.tsx
  src/components/detail/DateRagePicker.tsx
  src/components/detail/KakaoMap.tsx
  src/components/detail/PersonInput.tsx
  src/components/detail/ReservationButton.tsx
Labels: enhancement, design

#81 Feat: connect API with main page & products page
  package-lock.json
  public/images/main/carousel01.jpg
  public/images/main/carousel02.jpg
  public/images/main/carousel03.jpg
  public/images/main/winter01.jpg
  public/images/main/winter02.jpg
  public/images/main/winter03.jpg
  public/images/main/winter04.jpg
  public/svg/mainIcon/hotel.svg
  src/app/category/page.tsx
  src/app/page.tsx
  src/app/products/page.tsx
  src/components/category/AccommodationCard.tsx
  src/components/category/Dropdown.tsx
  src/components/category/InfiniteScrollContainer.tsx
  src/components/category/YourItemComponent.tsx
  src/components/main/Carousel.tsx
  src/components/main/ChristmasPensionList.tsx
  src/components/main/IconList.tsx
  src/components/main/IconWithLabel.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/Navigation.tsx
  src/components/main/PensionCard.tsx
  src/components/main/WinterHotelList.tsx
  src/components/main/WinterLocationList.tsx
  src/components/products/DropdownCategory.tsx
  src/components/products/DropdownLocation.tsx
  src/components/products/YourItemComponent.tsx
Labels: enhancement, design

#86 Feat: restore API func
  src/@types/cart.types.ts
  src/api/cartRequest.ts
  src/api/detailInfoRequest.ts
  src/api/orderRequest.ts
  src/app/api/orderRequest.ts
  src/app/detail/[id]/page.tsx
  src/app/reservation/[orderToken]/page.tsx
  src/app/reservationConfirm/[orderId]/page.tsx
  src/components/detail/CartButton.tsx
  src/components/detail/ReservationButton.tsx
Labels: bug

#100 Feat: infinite scroll and main data clean up & products error solved
  package-lock.json
  package.json
  src/app/products/page.tsx
  src/components/main/ChristmasPensionList.tsx
  src/components/main/WinterHotelList.tsx
Labels: enhancement

#107 Fix: all category all location select to product page
  src/app/products/page.tsx
  src/components/main/ChristmasPensionList.tsx
  src/components/main/WinterHotelList.tsx
Labels: enhancement
