Repository Dont12/KDT_Y_FE_Mini-Project, pull requests merged in 2023-12, with the labels that each got.

#129 Refactor: detail page Image size issue and kakomap rendering issue
  src/@types/detail.types.ts
  src/app/detail/[id]/page.tsx
  src/components/detail/Carousel.tsx
  src/components/detail/DateRagePicker.tsx
  src/components/detail/KakaoMap.tsx
  src/utils/todayTomorrow.ts
Labels: bug, refactor

#138 Feat: add media query in detail page and remove auth checking step
  src/api/detailInfoRequest.ts
  src/app/detail/[id]/page.tsx
  src/components/detail/CartButton.tsx
  src/components/detail/DateRagePicker.tsx
  src/components/detail/PersonInput.tsx
  src/components/detail/ReservationButton.tsx
  src/styles/dateRangePicker.css
  tailwind.config.ts
  tsconfig.json
Labels: enhancement, refactor

#147 Refactor: clean up types & api request
  src/@types/main.types.ts
  src/@types/products.types.ts
  src/api/productRequest.ts
  src/app/products/page.tsx
  src/components/main/ChristmasPensionList.tsx
  src/components/main/IconList.tsx
  src/components/main/MainCarousel.tsx
  src/components/main/WinterHotelList.tsx
  src/components/main/WinterLocationList.tsx
  src/components/products/DropdownCategory.tsx
  src/components/products/DropdownLocation.tsx
  src/components/products/ProductCard.tsx
Labels: refactor
